### ISSUE TITLE
Project Browser is filled with TinyIDE stacks

### ISSUE THREAD

**Issue by kdjanz** [AndyPiddock/TinyIDE#12]
Is there a way to hide the TinyIDE stacks in the Project Browser? Your files swamp the ones I'm trying to work on.

Thanks
Kelly Janz
kdjanz - at - porta dot ca

**Comment by AndyPiddock** [comment]
Hi Kelly, sorry about the late reply.

Yes the way LiveCode treats behavior stacks for plugins is not ideal., I had a few years back asked for an enhancement which would allow the user the option to hide stacks and scripts from the project browser if the stacks were in the plugins folder, I must revisit this.

I'm at this very moment building a no behavior version of TinyIDE. When I've completed this I will send you a copy to try out, this should be later today or tomorrow.

All the best
Andy

**Comment by kdjanz** [comment]
Thanks. I’ll look for that.

Kelly

**Comment by AndyPiddock** [comment]
Hi Kelly, in the folder 1 stack version, you will find a single stack version of TinyIDE.
I haven't had time to fully test all of the functions yet, so please let me know if you find any problems.

All the best
Andy
