### ISSUE TITLE
Classic and Graphic controls turn invisible in 9.0.0 RC1

### ISSUE THREAD

**Issue by madpink** [AndyPiddock/TinyIDE#2]
This occurs when I start up 9.0.0 RC1, and occasionally when I go to another program and then return to Livecode. The buttons for the Classic controls and the graphics turn invisible. They can still be clicked on, dragged onto stacks and hovertext explaining what they are still appear. Widgets do not disappear.

Opening the settings panel and then clicking save and close will make them appear again

Happens on multiple machines, all running MacOS 10.13.3, have not witnessed this using LC 8.1.9

**Comment by AndyPiddock** [comment]
Have you tried the version now here on GitHub? 
This version was worked on by bwmilby before it was added to GitHub.

**Comment by AndyPiddock** [comment]
OK, just tried this with the version here on 9.0  rc1 and can see the same problem. Looking at this today.

**Comment by AndyPiddock** [comment]
It seems that the DP 9 series and more so RC1 have a longer startup time than V8. 
Ive added a 2 second delay with messages in preOpenStack that seems to stop the issue... can you confirm please.

Only this behavior file touched , TinyIDE/TinyIDE_Behaviors/stack_revTinyIDE_35305.livecodescript

**Comment by madpink** [comment]
confirmed, that did the trick
