### ISSUE TITLE
Show group scripts

### ISSUE THREAD

**Issue by adxsoft** [AndyPiddock/TinyIDE#9]
Hi Andy
Found that group scripts were not showing up in CodePeek. Added the following code in button_BtnFSHoverInfo_13660. It will show group scripts if 'Selected Grouped' is switched on. When 'Selected Grouped' is off will show the control in the group.

default
                  # no keys held down show script of control
                  set the backgroundcolor of fld "CodeList" of stack "CodePeek" to "black"
                  try
                     if the icon of button "Select Grouped" of stack "revMenuBar" is 101046 then
                        # Select Groupd is on
                        put "GROUP SCRIPT" & cr & the script of gGroupID into tScript
                        put the number of lines of the script of gGroupID into tSL
                     else
                        put "OBJECT SCRIPT" & cr & the script of the target into tScript
                        put the number of lines of the script of the target into tSL
                     end if 

and function GroupOf

function GroupOf pControl
   local theCharNo
   
   put the long id of pControl into pControl ## force the long id
   
   if word 1 of pControl is not "card" then
      put offset(" of group ", pControl) into theCharNo
      if theCharNo > 0 then
         delete char 1 to (theCharNo + 3) of pControl
      else
         put empty into pControl
      end if
   end if
   return pControl
end GroupOf

Allan

**Comment by adxsoft** [comment]
Also in button_BtnFSHoverInfo_13660 changed the cases for group custom properties and txt property display as follows

case the CommandKey is down
                  # show text property of object (if it has a text property)
                  # CommandKey should also detect the Control Key on Windows and Linux Systems
                  try
                     set the backgroundcolor of fld "CodeList" of stack "CodePeek" to "dark green"
                     if the cpCodePeek of stack gStackName is "true" then
                        
                        if the icon of button "Select Grouped" of stack "revMenuBar" is 101046 then
                           # Select Groupd is on
                           put "GROUPS HAVE NO TEXT PROPERTY" into fld "CodeList" of stack "CodePeek"
                           break
                        else
                           put "TEXT PROPERTY" & cr & the text of the target into tProperty
                        end if
                        if the openStacks contains "CodePeek" is false then
                           open stack "CodePeek"
                           put tProperty into fld "CodeList" of stack "CodePeek"
                        end if
                        put tProperty into fld "CodeList" of stack "CodePeek"
                     end if
                  catch errorMess
                  end try
                  break

and ...

case the OptionKey is down
                  # show the custom properties of this control
                  set the backgroundcolor of fld "CodeList" of stack "CodePeek" to "dark blue"
                  try
                     if the cpCodePeek of stack gStackName is "true" then
                        if the openStacks contains "CodePeek" is false then
                           open stack "CodePeek"
                        end if
                        put empty into tObject
                        put "CUSTOM PROPERTIES" & cr  into fld "CodeList" of stack "CodePeek"
                        if the icon of button "Select Grouped" of stack "revMenuBar" is 101046 then
                           repeat for each line tKey in the customKeys of gGroupID
                              put the tKey of gGroupID into tProperty
                              put tKey & tab & tProperty  & cr after fld "CodeList" of stack "CodePeek"
                           end repeat
                        else
                           repeat for each line tKey in the customKeys of the target
                              put the tKey of the target into tProperty
                              put tKey & tab & tProperty  & cr after fld "CodeList" of stack "CodePeek"
                           end repeat
                        end if
                     end if
                  catch errorMess
                  end try
                  break

**Comment by AndyPiddock** [comment]
Many thanks Allan. Theses now added.
